name: 🐛 Bug Report
description: File a bug report to help us improve PerfScope
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched the existing issues for this bug
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version of PerfScope
          required: true

  - type: input
    id: version
    attributes:
      label: PerfScope version
      description: What version of PerfScope are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python version
      description: What version of Python are you using?
      options:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: How can we reproduce this?
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        ```python
        from perfscope import profile

        @profile()
        def example_function():
            # Your code here
            pass
        ```
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
