name: 🚀 Feature Request
description: Suggest an idea for PerfScope
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out this form as completely as possible.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched the existing issues and feature requests
          required: true
        - label: I have read the documentation
          required: true
        - label: This feature would be useful for the broader PerfScope community
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Performance Monitoring
        - Memory Profiling
        - Report Generation
        - Web Framework Integration
        - Visualization
        - Configuration
        - CLI/API
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Please provide a detailed use case for this feature
      placeholder: |
        Describe your specific use case:
        - What are you trying to accomplish?
        - How would this feature help?
        - What's your current workaround (if any)?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        If you have ideas about implementation:
        - API design suggestions
        - Code examples
        - Technical considerations

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
